### ISSUE TITLE
Add QUIC to transport documentation

### ISSUE THREAD

**Issue by DannyS03** [libp2p/docs#189]
Follows: https://github.com/libp2p/docs/issues/187#issuecomment-1241627105
Content is missing: https://github.com/libp2p/docs/issues/17#issuecomment-1228658994

> In our intent to add content for WebTransport, there is no existing content on QUIC to bounce off of

**Comment by marten-seemann** [comment]
Really happy to see this happen!

We probably don't need to go into a lot of depth how the QUIC protocol works. There's a lot of great content about that on the internet that we can link to (both blog posts and talks available on Youtube). Happy to provide pointers.

What we should describe is how libp2p uses QUIC, in particular:
1. How the handshake works (it's using the libp2p TLS 1.3 handshake, which encodes the peer certificate into the TLS certificate). We can probably link to the TLS section (once we have one)
2. We should highlight the fact that we don't need any additional security handshake and stream muxer, because QUIC provides all of this out of the box
3. We can highlight how fast a QUIC handshake is (counting roundtrips)
