### ISSUE TITLE
Body text can be a little hard to read on Firefox / Linux

### ISSUE THREAD

**Issue by travisperson** [libp2p/docs#26]
_Note: if you click into any of these links they are much easier to read. However, the images are much larger than they render on my screen, the inline Github images are a bit smaller but are closer to how they appear on my screen._

--------------------------

Given that documentation is a text heavy website, I think we should consider increasing the font-weight to help improve the contrast. I'm not sure what this looks like on OSX (probably, amazing), but at least on Linux the font rendering it's quite there and it's a tad bit hard to read.

**Current**
![2019-03-14-094515_1601x1123_scrot](https://user-images.githubusercontent.com/165274/54375233-e4f93f00-463d-11e9-81da-12c244c28fb4.png)

**400 font-weight**
![2019-03-14-094538_1601x1123_scrot](https://user-images.githubusercontent.com/165274/54375240-e88cc600-463d-11e9-9f47-6073569653e2.png)

**Comment by raulk** [comment]
## Collection of thoughts

**Typeface and font**

Pleasant docs sites like [Stripe](https://stripe.com/docs/quickstart) and [Zapier](https://zapier.com/developer/documentation/v2/) use font-weight 400, with explicit fonts for predictable results across platforms. They are usually sans-serif. I'm having second thoughts about using system-ui. Consider:

* IBM Plex Sans for prose, IBM Plex Mono for code.
* Fira Sans for prose, Fira Mono (with ligatures, yay!) for code.

**Text arrangement**

Make text at most 800px wide so that lines don't stretch too much. Lightening the tone of body text and slightly colouring it with a tint of #14152D (which @akrych picked for our libp2p backgrounds and harmonises much better with the brand than pure grey -- consider this for the sidebar background too). 

Centring the layout would also go a long way.

**Vertical rhythm**

Investing in vertical rhythm always goes a long way in terms of readability:

* https://iamsteve.me/blog/entry/a-guide-to-vertical-rhythm
* https://www.gridlover.net/

**References and inspiration**

* https://docsify.js.org/
* https://github.com/lord/slate
* https://docs.readthedocs.io/en/latest/intro/getting-started-with-sphinx.html

(let me know if you need more).

---

Yes, you guessed it: I'm a total typography nut 🤓

**Comment by raulk** [comment]
I played a little with the Chrome Inspector. Font is IBM Plex Sans, typography colours are changed, sidebar too, line spacing, and a few other things. Let me know if you like them and I'll post the details:

![image](https://user-images.githubusercontent.com/1101242/54386186-506bfc80-4690-11e9-8bb2-e225c523fdff.png)

**Comment by raulk** [comment]
* body text colour: rgba(20, 21, 45, 0.85)
* headings: #14152D
* line-height: 1.75rem.
* body width: 800px.
* all fonts: "IBM Flex Sans", available on Google Fonts: https://fonts.google.com/specimen/IBM+Plex+Sans.
* sidebar bg: #14152D
* sidebar active row: hsla(238, 38%, 23%, 1)

**Comment by yusefnapora** [comment]
nice, thanks for reporting the readability issue @travisperson - I'm all for upping the font weight.

I'll play with your styling changes @raulk, I like the look a lot

**Comment by yusefnapora** [comment]
Hopefully the PR above makes it easier to read @travisperson - if not feel free to open another issue.
