### ISSUE TITLE
Getting Started with NodeJs-Libp2p failing with latest libp2p-tcp version

### ISSUE THREAD

**Issue by vasa-develop** [libp2p/docs#65]
### Problem
While going through the [Getting Started docs for NodeJs](https://docs.libp2p.io/tutorials/getting-started/javascript/), I realized that the current version of `libp2p-tcp@0.14.1` is causing some problems. Below is the stack trace:

![err](https://user-images.githubusercontent.com/28847087/65905941-2e915780-e3df-11e9-8db5-8d940664b68a.png)

### Solution
I replaced the newer version of `libp2p-tcp` with `libp2p-tcp@"^0.13.2`, and it worked fine. So either we can freeze the version(add the working version in from of the installation script provided) or fix the current version.

**Comment by raulk** [comment]
@jacobheun @vasco-santos could you investigate what's going on here?

@yusefnapora mind overseeing that this is solved (whether in the bug is in docs, js, or in usage)?

**Comment by vasco-santos** [comment]
Hey @vasa-develop 

We are in the process of migrating all our codebase to use `async await` and `async iterators`. As this has been an iterative approach, there are some modules that are already released with these new APIs, while others are not yet ready.

In a short answer, the problem here is that you are installing the latest version of `libp2p-tcp`, which is already migrated for the new version. If you use `0.13.2` version, everything should work fine.

We currently have a warning about this on `js-libp2p` README (https://github.com/libp2p/js-libp2p#usage), which has not been good enough, as there have been other people with this type of issues. @yusefnapora any idea on how to improve this on our end? Meanwhile, myself and @jacobheun will probably change the latest releases to point to the non async version, in order to try to mitigate this issue.

**Comment by jacobheun** [comment]
The tags have been corrected on libp2p-tcp, so `npm i libp2p-tcp` will give you 0.13.2. We'll be marking the async versions of the libraries with `beta` tags, https://github.com/libp2p/js-libp2p/issues/460, to avoid this problem with the other converted modules.

**Comment by yusefnapora** [comment]
nice work @jacobheun, that seems like a good solution while things are still in flux.

**Comment by vasa-develop** [comment]
Seems good to me :)

**Comment by vasa-develop** [comment]
It's ok from my side. Feel free to close the issue, if you think it's done.
